server:
  port: 8050
  servlet:
    context-path: /storelocator

google:
  api:
    key: AIzaSyBu0GUKiUnrc20TGT2I4WJxV25oqPOYf7g
 
swagger:
  info: Get Stores info
  basePackage: com.gcp.storelocator.controller

#To connect in mysql local instance 
#spring.datasource.url: jdbc:mysql://localhost:3306/storelocator
#spring.datasource.username: root
#spring.datasource.password: root

#To connect in mysql cloud instance 
spring.datasource.url: jdbc:mysql://35.188.194.91:3306/backend
spring.datasource.username: backend
spring.datasource.password: backend

spring.jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.properties.hibernate.show_sql: true
spring.jpa.properties.hibernate.use_sql_comments: true
spring.jpa.properties.hibernate.format_sql: true


store:
  searchResultsLimit: 10
  radius: 5 
  #0.180874346591422

logging.level.root: INFO
logging.pattern.console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"

store.searchStores.timeout: 2

