apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendcartservice
  labels:
    app: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: spring-backend
        image: gcr.io/next-2019/ecomm/backendcart:v1
        ports:
        - containerPort: 80
