apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendregistration
  labels:
    app: reg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reg
  template:
    metadata:
      labels:
        app: reg
    spec:
      containers:
      - name: spring-backend
        image: gcr.io/next-2019/ecomm/backendreg:v1
        ports:
        - containerPort: 80
